Arithmetic with R

```{r}
5 + 5 -3
10-2
3*5
(5+5)/2
28%%6

```

Variable assignment

```{r}
x <- 10
x

y <- 9

x+y
result <- x-y
result


```

Basics data types in R

```{r}

my_numeric <- 423.80
my_character <- "universe"
my_logical <- FALSE  

class(my_numeric)
class(my_character)
class(my_logical)

```


Crate a vector

```{r}

numeric_vector <- c(1,10,49)
numeric_vector

character_vector <- c("a","b","c")

boolean_vector <- c(TRUE,FALSE,TRUE)

character_vector
boolean_vector


poker_vector <- c(140,-50,-20,-120,240)
roulette_vector <- c(-24,-50,10,350,10)

poker_vector

```

Naming a vector

```{r}

names(poker_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
poker_vector

names(roulette_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
roulette_vector

days <- c("Monday","Tuesday","Wednesday","Thursday","Friday")

names(poker_vector) <- days
poker_vector

```

Selection by comparison

```{r}
age <- 21
age >= 18

selection_vector <- poker_vector > 0
selection_vector

poker_winning_days <- poker_vector[selection_vector]
poker_winning_days

```
Calculating

```{r}
x_vector <- c(4,7,9)
y_vector <- c(12,45,78)

result_vector <- y_vector + x_vector
result_vector
```

Vector selection
```{r}
poker_vector
poker_vector[3]
poker_vector[c(2,3,4)]
poker_vector[2:5]
```

Matrices

```{r}
matrix(1:9,byrow=TRUE, nrow=3)
```
Matrix

```{r}
star_wars_matrix

star_wars_matrix[1,2]
star_wars_matrix[1:2,2]

star_wars_matrix[c(1,3),1]
star_wars_matrix[c(1,3)]
```

Arithmetic with mtraices

```{r}
mean <- star_wars_matrix /5
mean *2
```


Factor

```{r}
sex_vector <- c("Male","Female","Female","Male","Male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector
```
```{r}
temperature_vector <- c("High","Low","High","Low","Medium")
factor_temperature_vector <- factor(temperature_vector,order = TRUE,levels=c("Low","Medium","High"))
factor_temperature_vector
```

Factor Levels

```{r}
survey_vector <- c("M","F","F","M","M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector
levels(factor_survey_vector)<- c("Female","Male")
factor_survey_vector

```
```{r}
summary(factor_survey_vector)
```

Ordered factor
```{r}
male <- factor_survey_vector[1]
female <- factor_survey_vector[2]


speed_vector <- c("medium","slow","slow","medium","fast")
factor_speed_vector <- factor(speed_vector,ordered=TRUE,levels=c())

```

