---
title: "R Notebook"
output: html_notebook
---

```{r}
pow_two <- function(args){
  return(args^2)
}
pow_two(2)

sub_abs <- function(arg1,arg2){
  return(abs(arg1)+abs(arg2))
}
sub_abs(-2,3)

hello <- function(){
  print('Hi There!')
  return(TRUE)
}
hello()

pow_two <- function(x, print_info=TRUE){
  y <- x^2
  if(print_info){
    print(paste(x,"to the power two equals",y))
  }
  return(y)
}
pow_two(3,FALSE)

interpret <- function(num_views){
  if(num_views > 15){
    print("you are popular!")
    return(num_views)
  } else {
    print("try to be more visible!")
    return(0)
  }
}
interpret(linkedin[1])

interpret_all <- function(views, return_sum=TRUE){
  count <- 0
  for(v in views){
    count <- count+interpret(v)
  }
  
  if(return_sum){
    return(count)
  } else {
    return(NULL)
  }
}
interpret_all(linkedin)
```
```{r}
install.packages("gplot")
library(ggplot2)
gplot2(mtcars$wt, mtcars$hp)

```
lapply
```{r}
pioneers <- c("GAUSS:1777","BAYES:1702","PASCAL:1623","PEARSON:1857")
split_math <- strsplit(pioneers,split=":")
split_low <- lapply(split_math, tolower)

select_first <- function(x){
  x[1]
}

names <- lapply(split_low, select_first)
names

```
lapply and anonymous function
```{r}
names <- lapply(split_low, function(x){x[1]})
years <- lapply(split_low, function(x){x[2]})
names
years
```
use lapply with additional arguments
```{r}
select_el <- function(x,index){
  x[index]
}

select_el(split_low)

names <- lapply(split_low,select_el,1)
years <- lapply(split_low,select_el,2)

names
years
```
sapply
```{r}
names <- sapply(split_low ,select_el,1)

extreme_avg <- function(x){
  ((min(x)+max(x))/2)
}

vect1 <- c(3,6,7,6)
vect2 <- c(8,8,7,2)
vect3 <- c(10,1,11,6)

temp <- list(vect1,vect2,vect3)

sapply(temp, extreme_avg)
lapply(temp, extreme_avg)


```
Mathematical utilities
```{r}
errors <- c(1,9,-3,6,4,0,-9,5,-3,4,7,3)
print(sum(abs(errors)))
```