

```{r}
library(tidyverse)
sets <- read_csv('sets.csv')
themes <- read_csv('themes.csv')
parts <- read_csv('parts.csv')
part_category <- read_csv('part_category.csv')
inventory_parts <- read_csv('inventory_parts.csv')
inventories <- read_csv('inventories.csv')
colors <- read_csv('colors.csv')
parts
part_category
```


```{r}
parts %>%
	inner_join(part_category, by=c("part_cat_id"="id"))
```

Joining parts and inventories

```{r}
parts
inventory_parts
parts %>%
	inner_join(inventory_parts, by="part_num") ## Solo sucede cuando el nombre de la columna se repite en ambas tablas
inventory_parts %>%
	inner_join(parts, by="part_num")
```


Joining three tables

```{r}
sets
inventories
sets %>%
	inner_join(inventories, by="set_num") %>%
	inner_join(inventory_parts, by=c("id","inventory_id")) %>%
	inner_join(colors, by=c("color_id"="id"), suffix=c("_set","_color"))
```

what's the most common color?

```{r}
sets %>%
	inner_join(inventories, by="set_num") %>%
	inner_join(inventory_parts, by=c("id","inventory_id")) %>%
	inner_join(colors, by=c("color_id"="id"), suffix=c("_set","_color")) %>%
	count(name_color) %>%
	arrange(desc(n))
```


Left and Right Joins

```{r}
inventory_parts_joines <- sets %>%
	inner_join(inventories, by="set_num") %>%
	inner_join(inventory_parts, by=c("id","inventory_id")) %>%
	inner_join(colors, by=c("color_id"="id"), suffix=c("_set","_color")) %>%
	select(set_num, part_num, color_id, quantity)
inventory_parts_joines
millenium_fallcon <- inventory_parts_joines %>%
	filter(set_num == "7965-1")
star_destroyer <- inventory_parts_joines %>%
	filter(set_num == "75190-1")
millenium_fallcon %>%
	left_join(star_destroyer, by = c("part_num","color_id"), suffix=C("_falcon","_star_destroyer"))
```


Left joining two sets by color 

```{r}
millenium_fallcon_colors <- millenium_fallcon %>%
	group_by(color_id) %>%
	summarize(total_quantity=sum(quantity))
star_destroyer_colors <- star_destroyer %>%
	group_by(color_id) %>%
	summarize(total_quantity=sum(quantity))
millenium_fallcon_colors %>%
	left_join(star_destroyer_colors, by ="color_id", suffix=C("_falcon","_star_destroyer"))
```


```{r}
inventory_version_1 <- inventories %>%
	filter(version==1)
sets %>%
	left_join(inventory_version_1, by="set_num") %>%
	filter(is.na(version))
```

Right Join

```{r}
parts %>%
	count(part_cart_id) %>%
	right_join(part_categories, by=c("part_cat_id","id"))
```