---
title: "Sesión 3"
output: html_document
date: "2022-07-23"
---

```{r}
"Rarchitect" != "rarchitect"
```
Compare Vector
```{r}
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,9,16,5,2,13,14)

linkedin > 15
facebook <= 5
linkedin > facebook

```
Compare matrix
```{r}
views <- matrix(c(linkedin,facebook), nrow =2, byrow = TRUE)
views

views == 13
views <= 14
```

```{r}
linkedin
head(linkedin,3) #obtiene los primeros tres elementos
tail(linkedin,3) #obtiene los últimos tres elementos

last <- tail(linkedin,1) #obtiene el último elemento

last > 5 | last < 10
last > 15 & last <= 20
```
If Statement
```{r}
medium <- "Linkedin"
num_views <- 14

if(medium == "Linkedin"){
  print("Showing Linkedin information")
} else if(medium == "Facebook"){
  print("Showing Facebook information")
} else {
  print("Unknown medium")
}

if(num_views > 15){
  print("You are popular")
} else if(num_views <= 15 & num_views > 10){ 
  print("Your number of views is average")
}else {
  print("Try to be more visible")
}

```

```{r}
result <- ""
number <- 6

if(number < 10){
  if(number < 5){
    result <- "extra small"
  } else {
    result <- "small"
  }
} else if(number < 100){
  result <- "medium"
} else {
  result <- "large"
}

print(result)
```
write a while loop
```{r}
speed <- 64
while(speed > 30){
  print("Slow down!")
  speed <- speed -7
}

speed
```
```{r}
speed <-70
while(speed > 30){
  print(paste("Your speed is", speed))
  if(speed >= 48){
    print("Slow down big time")
    speed <- speed - 11
  } else {
    print("Slow down")
    speed <- speed -6
  }
}
```

Break
```{r}
speed <- 78
while(speed > 30){
  print(paste("Your speed is",speed))
  if(speed > 80){
    break
  }
  
  if(speed > 48){
    print("Slow down big time")
    speed <- speed -11
  } else {
    print("Slow down")
    speed <- speed -6
  }
}
```

```{r}
i <- 1
while(i <= 10){
  print(3*i)
  if((i*3)%%8 == 0){
    break
  }
  i <- i+1
}
```
Loop over a vector
```{r}
linkedin <- c(16,9,13,5,2,17,14)
for(i in linkedin){
  print(i)
}

for(i in 1:length(linkedin)){
  print(linkedin[i])
}

```
Loop over a list
```{r}
nyc <- list(pop=8405837, c("Manhathan","Bronx","Brooklyn","Queens"), capital=FALSE)

for(n in nyc){
  print(n)
}

for(i in 1:length(nyc)){
  print(nyc[i])
}

```
Loop over a matrix
```{r}
new_hope <- c(460.998,314.4)
empire_strikes <- c(290.475,247.900)
return_jedi <- c(309.306,165.8)

box_office  <- c(new_hope, empire_strikes, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow = TRUE, nrow=3)
stars_wars_matrix

for(i in 1:nrow(stars_wars_matrix)){
  for(j in 1:ncol(stars_wars_matrix)){
    print(paste("row:",i,"col",j,"contain:",stars_wars_matrix[i,j]))
  }
}

```

```{r}
for(li in linkedin){
  if(li>10){
    print("you are popular")
  }
  else {
    print("be more visible")
  }
  
  if(li>16){
    print("this is ridiculous i'm outta here!")
    break
  }
  
  if(li<5){
    print("this is too embarassing!")
    break
  }
  
  print(li)
}
```

```{r}
```
